# Translations template for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-10-28 10:15+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.15.0\n"

#: geovisio/templates/main.html:45
msgid "Simple 360Â° geolocated pictures hosting"
msgstr ""

#: geovisio/templates/main.html:47
msgid "Full page version"
msgstr ""

#: geovisio/templates/main.html:51
msgid "Viewer"
msgstr ""

#: geovisio/templates/main.html:52
msgid "Embed pre-configured viewer"
msgstr ""

#: geovisio/templates/main.html:53
msgid "Easiest way to have a working GeoVisio viewer on your website"
msgstr ""

#: geovisio/templates/main.html:59
msgid "Use JS library"
msgstr ""

#: geovisio/templates/main.html:60
msgid "A completely configurable viewer for your website"
msgstr ""

#: geovisio/templates/main.html:82
msgid "Links"
msgstr ""

#: geovisio/templates/main.html:84
msgid "Pictures viewer"
msgstr ""

#: geovisio/templates/main.html:86
msgid "API docs"
msgstr ""

#: geovisio/templates/main.html:88
msgid "JS library docs"
msgstr ""

#: geovisio/templates/main.html:90
msgid "Repositories"
msgstr ""

#: geovisio/templates/viewer.html:22
msgid "You need to enable JavaScript to run this app."
msgstr ""

#: geovisio/utils/auth.py:201
msgid "Authentication is mandatory"
msgstr ""

#: geovisio/utils/auth.py:330
msgid "Only Bearer token are supported"
msgstr ""

#: geovisio/utils/excluded_areas.py:82
msgid "Impossible to find excluded area"
msgstr ""

#: geovisio/utils/pictures.py:303
#, python-format
msgid ""
"Invalid '%(format)s' format for image, only the following formats are "
"available: %(allowed_formats)s"
msgstr ""

#: geovisio/utils/pictures.py:417
msgid "Picture can't be found, you may check its ID"
msgstr ""

#: geovisio/utils/pictures.py:420
msgid "Picture is not available (either hidden by admin or processing)"
msgstr ""

#: geovisio/utils/pictures.py:428
msgid "HD Picture file is not available"
msgstr ""

#: geovisio/utils/pictures.py:447
msgid "Picture derivates file are not available"
msgstr ""

#: geovisio/utils/pictures.py:464 geovisio/web/pictures.py:53
#: geovisio/web/pictures.py:98 geovisio/web/pictures.py:208
msgid "Unable to read picture on filesystem"
msgstr ""

#: geovisio/utils/reports.py:142 geovisio/utils/upload_set.py:352
#: geovisio/web/params.py:356
msgid "Unsupported filter parameter"
msgstr ""

#: geovisio/utils/sequences.py:377
msgid ""
"Sort by file date is not possible on this sequence (no file date "
"information available on pictures)"
msgstr ""

#: geovisio/utils/sequences.py:402
#, python-format
msgid ""
"Sort using %(sort)s is not possible on this sequence, picture %(pic)s is "
"missing mandatory metadata"
msgstr ""

#: geovisio/utils/sequences.py:590 geovisio/web/collections.py:618
#, python-format
msgid "Collection %(c)s wasn't found in database"
msgstr ""

#: geovisio/utils/tokens.py:42
msgid "JWT token signature does not match"
msgstr ""

#: geovisio/utils/tokens.py:56
msgid "Token does not exist anymore"
msgstr ""

#: geovisio/utils/tokens.py:60
msgid ""
"Token not yet claimed, this token cannot be used yet. Either claim this "
"token or generate a new one"
msgstr ""

#: geovisio/utils/upload_set.py:158
msgid ""
"The picture is too similar to another one (nearby and taken almost at the"
" same time)"
msgstr ""

#: geovisio/utils/upload_set.py:161
msgid "The sent file is not a valid JPEG"
msgstr ""

#: geovisio/utils/upload_set.py:164
msgid "The picture has invalid EXIF or XMP metadata, making it impossible to use"
msgstr ""

#: geovisio/utils/upload_set.py:167
msgid "Something went very wrong, but not due to the picture itself"
msgstr ""

#: geovisio/web/auth.py:60
msgid "Impossible to finish authentication flow"
msgstr ""

#: geovisio/web/auth.py:64
msgid ""
"You can try to clear your cookies and retry. If the problem persists, "
"contact your instance administrator."
msgstr ""

#: geovisio/web/collections.py:288
#, python-format
msgid "There is no collection created after %(d)s"
msgstr ""

#: geovisio/web/collections.py:290
#, python-format
msgid "There is no collection created before %(d)s"
msgstr ""

#: geovisio/web/collections.py:399 geovisio/web/items.py:397
msgid "Collection doesn't exist"
msgstr ""

#: geovisio/web/collections.py:458
msgid "Impossible to find a thumbnail for the collection"
msgstr ""

#: geovisio/web/collections.py:578 geovisio/web/items.py:1174
msgid ""
"Picture visibility parameter (visible) should be either unset, true or "
"false"
msgstr ""

#: geovisio/web/collections.py:584
msgid ""
"Sequence title is not valid, should be a string with a max of 250 "
"characters"
msgstr ""

#: geovisio/web/collections.py:590
msgid "Sort order parameter is invalid"
msgstr ""

#: geovisio/web/collections.py:601
msgid ""
"Relative heading is not valid, should be an integer in degrees from -180 "
"to 180"
msgstr ""

#: geovisio/web/collections.py:622
msgid "You're not authorized to edit this sequence"
msgstr ""

#: geovisio/web/collections.py:631
#, python-format
msgid "Sequence %(c)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""

#: geovisio/web/collections.py:766
msgid "Sequence doesn't exists"
msgstr ""

#: geovisio/web/collections.py:911 geovisio/web/stac.py:337
#, python-format
msgid "Impossible to find user %(u)s"
msgstr ""

#: geovisio/web/collections.py:943 geovisio/web/stac.py:347
#, python-format
msgid "No data loaded for user %(u)s"
msgstr ""

#: geovisio/web/collections.py:945
msgid "No matching sequences found"
msgstr ""

#: geovisio/web/excluded_areas.py:133
msgid "You must be logged-in as admin to access all excluded areas"
msgstr ""

#: geovisio/web/excluded_areas.py:135
msgid "You're not authorized to access all excluded areas"
msgstr ""

#: geovisio/web/excluded_areas.py:172 geovisio/web/excluded_areas.py:182
#: geovisio/web/excluded_areas.py:336 geovisio/web/excluded_areas.py:343
msgid "Impossible to create an Excluded Area"
msgstr ""

#: geovisio/web/excluded_areas.py:174 geovisio/web/excluded_areas.py:338
msgid "Parameter for creating an Excluded Area should be a valid JSON"
msgstr ""

#: geovisio/web/excluded_areas.py:177 geovisio/web/excluded_areas.py:235
msgid "You must be logged-in as admin to edit excluded areas"
msgstr ""

#: geovisio/web/excluded_areas.py:230 geovisio/web/excluded_areas.py:242
msgid "Impossible to replace all Excluded Areas"
msgstr ""

#: geovisio/web/excluded_areas.py:232
msgid "Parameter for replacing all Excluded Areas should be a valid JSON"
msgstr ""

#: geovisio/web/excluded_areas.py:272
msgid "You must be logged-in as admin to delete excluded areas"
msgstr ""

#: geovisio/web/items.py:360
msgid "limit parameter should be an integer between 1 and 10000"
msgstr ""

#: geovisio/web/items.py:362
msgid "limit parameter should be a valid, positive integer (between 1 and 10000)"
msgstr ""

#: geovisio/web/items.py:367
msgid "`startAfterRank` and `withPicture` are mutually exclusive parameters"
msgstr ""

#: geovisio/web/items.py:374
msgid "startAfterRank parameter should be a positive integer (starting from 1)"
msgstr ""

#: geovisio/web/items.py:376
msgid "startAfterRank parameter should be a valid, positive integer"
msgstr ""

#: geovisio/web/items.py:403
#, python-format
msgid "No more items in this collection (last available rank is %(r)s)"
msgstr ""

#: geovisio/web/items.py:413
#, python-format
msgid "Picture with id %(p)s does not exists"
msgstr ""

#: geovisio/web/items.py:699
msgid "Item doesn't exist"
msgstr ""

#: geovisio/web/items.py:758
msgid "Search using POST method should have a JSON body"
msgstr ""

#: geovisio/web/items.py:767
msgid "Parameter limit must be either empty or a number between 1 and 10000"
msgstr ""

#: geovisio/web/items.py:823
msgid ""
"Parameter place_fov_tolerance must be either empty or a number between 2 "
"and 180"
msgstr ""

#: geovisio/web/items.py:845
msgid ""
"Parameter intersects should contain a valid GeoJSON Geometry (not a "
"Feature)"
msgstr ""

#: geovisio/web/items.py:861
msgid "Parameter ids should be a JSON array of strings"
msgstr ""

#: geovisio/web/items.py:873
msgid "Parameter collections should be a JSON array of strings"
msgstr ""

#: geovisio/web/items.py:884
msgid "Picture doesn't exist"
msgstr ""

#: geovisio/web/items.py:987 geovisio/web/upload_set.py:527
msgid "Content type should be multipart/form-data"
msgstr ""

#: geovisio/web/items.py:991
msgid "Missing \"position\" parameter"
msgstr ""

#: geovisio/web/items.py:998
msgid "Position in sequence should be a positive integer"
msgstr ""

#: geovisio/web/items.py:1012 geovisio/web/upload_set.py:336
msgid ""
"Longitude cannot be overridden alone, override_latitude also needs to be "
"set"
msgstr ""

#: geovisio/web/items.py:1014 geovisio/web/upload_set.py:338
msgid ""
"Latitude cannot be overridden alone, override_longitude also needs to be "
"set"
msgstr ""

#: geovisio/web/items.py:1015 geovisio/web/upload_set.py:311
#, python-format
msgid "For parameter `override_longitude`, `%(v)s` is not a valid longitude"
msgstr ""

#: geovisio/web/items.py:1016 geovisio/web/upload_set.py:316
#, python-format
msgid "For parameter `override_latitude`, `%(v)s` is not a valid latitude"
msgstr ""

#: geovisio/web/items.py:1035
msgid "Picture blur status should be either unset, true or false"
msgstr ""

#: geovisio/web/items.py:1039
msgid "No picture file was sent"
msgstr ""

#: geovisio/web/items.py:1045 geovisio/web/upload_set.py:377
msgid "Picture file is either missing or in an unsupported format (should be jpg)"
msgstr ""

#: geovisio/web/items.py:1052
#, python-format
msgid "Collection %(s)s wasn't found in database"
msgstr ""

#: geovisio/web/items.py:1056
msgid "You're not authorized to add picture to this collection"
msgstr ""

#: geovisio/web/items.py:1061
msgid "The collection has been deleted, impossible to add pictures to it"
msgstr ""

#: geovisio/web/items.py:1091
msgid "Picture at given position already exist"
msgstr ""

#: geovisio/web/items.py:1093 geovisio/web/upload_set.py:613
msgid "Impossible to parse picture metadata"
msgstr ""

#: geovisio/web/items.py:1095 geovisio/web/upload_set.py:620
msgid "Picture has invalid metadata"
msgstr ""

#: geovisio/web/items.py:1103 geovisio/web/upload_set.py:646
msgid "Picture wasn't correctly saved in filesystem"
msgstr ""

#: geovisio/web/items.py:1186
msgid ""
"Heading is not valid, should be an integer in degrees from 0Â° to 360Â°. "
"North is 0Â°, East = 90Â°, South = 180Â° and West = 270Â°."
msgstr ""

#: geovisio/web/items.py:1203 geovisio/web/items.py:1294
#, python-format
msgid "Picture %(p)s wasn't found in database"
msgstr ""

#: geovisio/web/items.py:1207 geovisio/web/items.py:1298
msgid "You're not authorized to edit this picture"
msgstr ""

#: geovisio/web/items.py:1217
#, python-format
msgid "Picture %(p)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""

#: geovisio/web/map.py:143
msgid "One of required parameter is empty"
msgstr ""

#: geovisio/web/map.py:145
msgid "Tile format is invalid, should be either pbf or mvt"
msgstr ""

#: geovisio/web/map.py:149 geovisio/web/map.py:151
msgid "X or Y parameter is out of bounds"
msgstr ""

#: geovisio/web/map.py:153
msgid "Z parameter is out of bounds (should be 0-15)"
msgstr ""

#: geovisio/web/map.py:164
msgid "Impossible to get tile"
msgstr ""

#: geovisio/web/params.py:98
msgid "Parameter datetime should contain one or two dates"
msgstr ""

#: geovisio/web/params.py:168
msgid ""
"Parameter bbox must contain valid longitude (-180 to 180) and latitude "
"(-90 to 90) values"
msgstr ""

#: geovisio/web/params.py:173
msgid "Parameter bbox must be in format [minX, minY, maxX, maxY]"
msgstr ""

#: geovisio/web/params.py:210
#, python-format
msgid "Parameter %(p)s must be coordinates in lat,lon format"
msgstr ""

#: geovisio/web/params.py:213
#, python-format
msgid "Longitude in parameter %(p)s is not valid (should be between -180 and 180)"
msgstr ""

#: geovisio/web/params.py:214
#, python-format
msgid "Latitude in parameter %(p)s is not valid (should be between -90 and 90)"
msgstr ""

#: geovisio/web/params.py:237 geovisio/web/params.py:250
#, python-format
msgid ""
"Parameter %(p)s is invalid (should be a distance range in meters like "
"\"5-15\")"
msgstr ""

#: geovisio/web/params.py:243
#, python-format
msgid "Parameter %(p)s has a min value greater than its max value"
msgstr ""

#: geovisio/web/params.py:317
#, python-format
msgid "Parameter %(p)s must be a valid list"
msgstr ""

#: geovisio/web/params.py:441
msgid "Unsupported sortby parameter: invalid column name"
msgstr ""

#: geovisio/web/params.py:449
msgid "Unsupported sortby parameter: syntax isn't correct"
msgstr ""

#: geovisio/web/params.py:475
#, python-format
msgid "limit parameter should be a valid, positive integer (between 1 and %(v)s)"
msgstr ""

#: geovisio/web/params.py:478
#, python-format
msgid "limit parameter should be an integer between 1 and %(v)s"
msgstr ""

#: geovisio/web/params.py:489
msgid "longitude needs to be between -180 and 180"
msgstr ""

#: geovisio/web/params.py:499
msgid "latitude needs to be between -90 and 90"
msgstr ""

#: geovisio/web/pictures.py:187
msgid "Tiles are not available for flat pictures"
msgstr ""

#: geovisio/web/pictures.py:192
msgid "Column parameter is invalid, should be an integer"
msgstr ""

#: geovisio/web/pictures.py:195
msgid "Column parameter is invalid"
msgstr ""

#: geovisio/web/pictures.py:200
msgid "Row parameter is invalid, should be an integer"
msgstr ""

#: geovisio/web/pictures.py:203
msgid "Row parameter is invalid"
msgstr ""

#: geovisio/web/reports.py:89 geovisio/web/reports.py:99
msgid "Impossible to create a Report"
msgstr ""

#: geovisio/web/reports.py:91
msgid "Parameter for creating a Report should be a valid JSON"
msgstr ""

#: geovisio/web/reports.py:144
msgid "Only authenticated users can access reports"
msgstr ""

#: geovisio/web/reports.py:148 geovisio/web/reports.py:266
msgid "Report doesn't exist"
msgstr ""

#: geovisio/web/reports.py:157
msgid "You're not authorized to access this report"
msgstr ""

#: geovisio/web/reports.py:277
msgid "You're not authorized to edit this Report"
msgstr ""

#: geovisio/web/reports.py:284
msgid "Impossible to edit the Report"
msgstr ""

#: geovisio/web/reports.py:286
msgid "Parameter for editing the Report should be a valid JSON"
msgstr ""

#: geovisio/web/reports.py:349 geovisio/web/reports.py:392
#: geovisio/web/upload_set.py:265 geovisio/web/upload_set.py:385
msgid "Impossible to parse parameters"
msgstr ""

#: geovisio/web/reports.py:352
msgid "You're not authorized to list reports"
msgstr ""

#: geovisio/web/rss.py:22
#, python-format
msgid "Sequence \"%(name)s\" by \"%(user)s\" was captured on %(date)s."
msgstr ""

#: geovisio/web/rss.py:40
msgid "View on the map"
msgstr ""

#: geovisio/web/rss.py:40
msgid "JSON metadata"
msgstr ""

#: geovisio/web/rss.py:49
msgid "GeoVisio collections"
msgstr ""

#: geovisio/web/rss.py:51
msgid "List of collections from this GeoVisio server"
msgstr ""

#: geovisio/web/tokens.py:100 geovisio/web/tokens.py:143
#: geovisio/web/tokens.py:231
msgid "Impossible to find token"
msgstr ""

#: geovisio/web/tokens.py:181
msgid "Impossible to generate a new token"
msgstr ""

#: geovisio/web/tokens.py:236
msgid "Token already claimed by another account"
msgstr ""

#: geovisio/web/upload_set.py:133
msgid "Impossible to create an UploadSet"
msgstr ""

#: geovisio/web/upload_set.py:135
msgid "Parameter for creating an UploadSet should be a valid JSON"
msgstr ""

#: geovisio/web/upload_set.py:181 geovisio/web/upload_set.py:214
#: geovisio/web/upload_set.py:724
msgid "UploadSet doesn't exist"
msgstr ""

#: geovisio/web/upload_set.py:216
msgid "You're not authorized to list pictures in this upload set"
msgstr ""

#: geovisio/web/upload_set.py:303
msgid ""
"Parameter `override_capture_time` is not a valid datetime, it should be "
"an iso formated datetime (like '2017-07-21T17:32:28Z')."
msgstr ""

#: geovisio/web/upload_set.py:370
msgid "No file was sent"
msgstr ""

#: geovisio/web/upload_set.py:534 geovisio/web/upload_set.py:710
#, python-format
msgid "UploadSet %(u)s does not exist"
msgstr ""

#: geovisio/web/upload_set.py:538
msgid "You're not authorized to add picture to this upload set"
msgstr ""

#: geovisio/web/upload_set.py:578
msgid "The item has already been added to this upload set"
msgstr ""

#: geovisio/web/upload_set.py:585
msgid "The same picture has already been sent in a past upload"
msgstr ""

#: geovisio/web/upload_set.py:628
msgid "Impossible to open file as image. The only supported image format is jpg."
msgstr ""

#: geovisio/web/upload_set.py:714
msgid "You're not authorized to complete this upload set"
msgstr ""

#: geovisio/web/upload_set.py:759
msgid "You're not authorized to delete this upload set"
msgstr ""

#: geovisio/web/users.py:84
msgid "Impossible to find user"
msgstr ""

#: geovisio/web/users.py:160
msgid ""
"No search parameter given, you should provide `q=<pattern>` as query "
"parameter"
msgstr ""

#: geovisio/web/utils.py:51
msgid "No default account defined, please contact your instance administrator"
msgstr ""

